name: 'GitHub Forker'
author: 'lelia'
branding:
  icon: 'git-branch'
  color: 'green'
description: 'GitHub action for automating fork creation'
inputs:
  token:
    description: 'GitHub API token with forking permissions'
    required: true
  owner:
    description: 'Owner of GitHub repository being forked'
    required: true
  repo:
    description: 'GitHub repository being forked'
    required: true
  org:
    description: 'GitHub organization to fork the repository into'
    required: false
  user:
    description: 'GitHub user requesting the fork'
    required: false
  checkUser:
    description: 'Enforce organization membership for GitHub user'
    required: false
    default: 'false'
  promoteUser:
    description: 'Promote GitHub user to admin of the forked repo'
    required: false
    default: 'false'
  licenseAllowlist:
    description: 'List of allowed licenses for repository being forked'
    required: false
    default: 'undefined'
outputs:
  forkUrl:
    description: 'The URL of the forked repository'
runs:
  using: 'node12'
  main: 'dist/index.js'
